title:            Data Intuitive
description:      ""
#description:      "Data where applicable, Intuition where needed"
url:              'https://www.data-intuitive.com'
# Permalink setting:
# - pretty is not good because it uses the post's tags to prepend to the path...
# The following format is compatible with the one we used on Wordpress.
# This means all internal links should still be valid.
permalink:        "/:year/:month/:title/"
markdown:         kramdown
highlighter:      rouge
lsi:              false
logo:             logo_white.png
default_bg:       graan-2-smaller.png
disqus_shortname: data-intuitive

# Make sure sharing buttons are placed on every page by default
share: true

owner:
  name:           Toni Verbeiren
  avatar:         toni1.png
  # Social networking links used in footer. Update and remove as you like.
  twitter:        DataIntuitive
  github:         data-intuitive

links:
  - title: Home
    url: /
    external: false
    #    icon: home
    #  - title: Services 
    #url: /offering
  - title: Careers 
    url: /about
    #- title: Featured Posts
    #url: /featured
  - title: Contact
    url: /contact

paginate: 10
category_dir: topics
category_title_prefix:
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp", ".gitignore", "TODO.md", "README.md", "_posts/*.Rmd"]
destination: public

gems: [jekyll-paginate]

include: ["tricks/tricks.md", "incertae/"]


kramdown:
  input: GFM
  syntax_highlighter: rouge
#  enable_coderay: true
#  math_engine: ritex
#   coderay:
#     coderay_css: class
#     coderay_line_numbers: 
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_wrap:              div
#    coderay_css:               style

#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6

# Redcarpet does syntax highlighting better than kramdown
#redcarpet:
#  extensions: ["footnotes", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# prose:
#    rooturl: '_posts'
#    siteurl: 'http://hmfaysal.github.io/Notepad/'
#    relativeLinks: 'http://hmfaysal.github.io/Notepad/links.jsonp'
#    media: 'images'
#   metadata:
#     _posts:
#       - name: "published"
#         field:
#           label: "Published"
#           element: "checkbox"
#           value: "true"
#       - name: "layout"
#         field:
#           element: "hidden"
#           label: "Layout"
#           value: "post"
#       - name: "title"
#         field:
#           label: "Title"
#           element: "text"
#           value: "An Awesome Headline!"
#       - name: "description"
#         field:
#           element: "text"
#           label: "Description"
#           placeholder: "Enter Post Description"
#       - name: "headline"
#         field:
#           element: "text"
#           label: "beadline"
#           placeholder: "Enter Post Headline"
#       - name: "modified"
#         field:
#           element: "text"
#           label: "Has this page been modified?"
#           placeholder: "YYYY-MM-DD"
#       - name: "categories"
#         field:
#           element: "multiselect"
#           label: "Add categories"
#           placeholder: "Choose categories"
#           value: personal
#           options:
#             - name: "Personal"
#               value: personal
#             - name: "Engineering"
#               value: engineering
#             - name: "Physics"
#               value: physics
#             - name: "Psychology"
#               value: psychology
#             - name: "Interesting"
#               value: interesting
#             - name: "Web-Development"
#               value: webdevelopment
#           alterable: true
#       - name: "tags"
#         field:
#           element: "text"
#           label: "Tags"
#           placeholder: "Enter tags, separated by spaces"
#       - name: "imagefeature"
#         field:
#           element: "text"
#           label: "Featured Image"
#           placeholder: "somefile.jpg"
#       - name: "mathjax"
#         field:
#           element: "checkbox"
#           label: "MathJax"
#           value: false
#       - name: "featured"
#         field:
#           element: "checkbox"
#           label: "Featured?"
#           value: false
#       - name: "comments"
#         field:
#           element: "checkbox"
#           label: "Comments"
#           value: false
